[build]
  command = "npm run build"
  publish = "dist/spa"

# Only keep this if you truly have Netlify Functions in netlify/functions
[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
