build.command: npm run build:client
publish: /opt/build/repo/dist/spa
functions.*.external_node_modules = ["express"]
  publish = "dist/spa"


[functions]
  node_bundler = "esbuild"
  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
